### PR TITLE
Adds section about middleware to README.md

### PR DESCRIPTION
**Pull request by rickharrison**
Please correct me if I'm wrong, but this enhancer needs to be added to the store before the middleware enhancer. I found this confusing while I got up and running so I added it to the README.

### CODE REVIEW

**Comment by ingro** [comment]
Thanks for the tip, was confused about how to use this library, this definetely should be merged :)

**Comment by danez** [comment]
+1

**Comment by gaearon** [comment]
I'd rather use `compose()` here and show that it needs to come _last in the composition chain_.
That's what most people are using when they have several store enhancers.

**Comment by tappleby** [comment]
@gaearon thanks for the note about `compose`, I've updated the README to include a more detailed usage explanation.

@rickharrison thanks for the original PR, middleware usage should be covered by the [latest doc updates](https://github.com/tappleby/redux-batched-subscribe/commit/5cde4b13e0dc87702870a9f3f7f8a1790136619b).

**Pull request closed without merging**
